<?php

namespace Tests\Unit\Http\Requests\Comments;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Comments\ReplyRequest
 */
class ReplyRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Comments\ReplyRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Comments\ReplyRequest();
    }

    /**
     * @test
     */
    public function rules()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'comment_body' => [
                'required',
                'min:3',
                'max:255',
            ],
            'comment_id' => [
                'required',
                'exists:comments,id',
            ],
            'article_id' => [
                'required',
                'exists:articles,id',
            ],
        ], $actual);
    }

    // test cases...
}
