<?php

namespace Tests\Feature\Http\Controllers\Client;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Client\BlogController
 */
class BlogControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function categories_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog.categories'));

        $response->assertOk();
        $response->assertViewIs('client.blog.categories');
        $response->assertViewHas('categories');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog'));

        $response->assertOk();
        $response->assertViewIs('client.blog.index');
        $response->assertViewHas('articles');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog.show', ['article' => $article]));

        $response->assertOk();
        $response->assertViewIs('client.blog.show');
        $response->assertViewHas('article');

        // TODO: perform additional assertions
    }

    // test cases...
}
