<?php

namespace Tests\Feature\Http\Controllers\Client;

use App\Models\Language\Language;
use App\Models\Navigation\Page;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Client\LanguageController
 */
class LanguageControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
        $language = Language::find(2);
        $response = $this->get(route('language', ['code' => 'en']));

        $response->assertRedirect(url('/'));
        foreach (Page::public()->get() as $page) {
            self::assertEquals(2, $page->language_id);
//            $response->assertSee($page->name);
        }

        // TODO: perform additional assertions
    }

    // test cases...
}
