<?php

namespace Tests\Feature\Http\Controllers\Client;

use App\Models\Navigation\Page;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\Feature\Http\Controllers\Admin\Helpers;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Client\PagesController
 */
class PagesControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /**
     * @test
     */
    public function home_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('index'));

        $response->assertOk();
        $response->assertViewIs('client.index');
        $response->assertViewHas('page');
        $response->assertSee(Page::where('url', 'home')->first()->text->content);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
        $page = Helpers::createPage();
        $response = $this->get(route('pages.show', ['page' => $page]));
        $response->assertOk();
        $response->assertSee($page->text->content);


        // TODO: perform additional assertions
    }

    // test cases...
}
