<?php

namespace Tests\Feature\Http\Controllers\Client;

use App\Models\Locations\Location;
use App\Models\Navigation\Page;
use App\Models\Reservations\Reservation;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\Feature\Http\Controllers\Admin\Helpers;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Client\ReservationController
 */
class ReservationControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $reservation = factory(Reservation::class)->create();

        $response = $this->actingAs($user)->delete(route('reservation.destroy', ['reservation' => $reservation]));

        $response->assertRedirect(url('/'));
        $this->assertSoftDeleted($reservation);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_reservations_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $location = Location::first();
        $response = $this->post(route('getReservations'), [
            'location' => $location->id,
        ]);

        $response->assertOk();
        $this->assertEquals(0,
            $response->baseResponse->getOriginalContent()
                ->diff($location->reservations()->get())->count());
        $this->assertEquals(0,
            $location->reservations()->get()
                ->diff($response->baseResponse->getOriginalContent())->count());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();

        $response = $this->actingAs($user)->get(route('reservation.index'));

        $response->assertRedirect(route('pages.show', ['page' => 'reservation']));
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $location = Helpers::createLocation();
        $data = [
            'location_id' => $location->id,
            'visitors_count' => $this->faker->randomNumber(),
            'from_date' => Carbon::now()->addHours(5)->format('d.m.Y H:i'),
            'to_date' => Carbon::now()->addHours(10)->format('d.m.Y H:i'),
        ];
        $response = $this->actingAs($user)->post(route('reservation.store'), $data);

        $response->assertRedirect(url(''));
        $this->assertDatabaseHas('reservations', [
            'location_id' => $location->id,
            'visitors_count' => $data['visitors_count'],
            'start_at' => Carbon::createFromFormat('d.m.Y H:i', $data['from_date'])->format('Y-m-d H:i:s'),
            'end_at' => Carbon::createFromFormat('d.m.Y H:i', $data['to_date'])->format('Y-m-d H:i:s'),
        ]);
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Client\ReservationController::class,
            'store',
            \App\Http\Requests\Reservations\StoreRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $reservation = factory(Reservation::class)->create();

        $data = [
            'location_id' => $reservation->location_id,
            'visitors_count' => $this->faker->randomNumber(),
            'from_date' => Carbon::now()->addHours(5)->format('d.m.Y H:i'),
            'to_date' => Carbon::now()->addHours(10)->format('d.m.Y H:i'),
        ];
        $response = $this->actingAs($user)->put(route('reservation.update', ['reservation' => $reservation]), $data);

        $response->assertRedirect(url('/'));
        $this->assertDatabaseHas('reservations', [
            'visitors_count' => $data['visitors_count'],
            'start_at' => Carbon::createFromFormat('d.m.Y H:i', $data['from_date'])->format('Y-m-d H:i:s'),
            'end_at' => Carbon::createFromFormat('d.m.Y H:i', $data['to_date'])->format('Y-m-d H:i:s'),
        ]);
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Client\ReservationController::class,
            'update',
            \App\Http\Requests\Reservations\UpdateRequest::class
        );
    }

    // test cases...
}
