<?php

namespace Tests\Unit\Http\Requests\Reservations;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Reservations\UpdateRequest
 */
class UpdateRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Reservations\UpdateRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Reservations\UpdateRequest();
    }

    /**
     * @test
     */
    public function rules()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'location_id' => [
                'required',
                'exists:locations,id',
            ],
            'visitors_count' => [
                'required',
                'integer',
                'min:1',
            ],
            'from_date' => [
                'required',
                'date',
                'after:now',
            ],
            'to_date' => [
                'required',
                'date',
                'after:from_date',
            ],
        ], $actual);
    }

    // test cases...
}
