<?php

namespace Tests\Feature\Http\Controllers\Admin;

use App\Models\Consoles\ConsoleType;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\ConsoleTypeController
 */
class ConsoleTypeControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();

        $response = $this->actingAs($user)->get(route('type.create'));

        $response->assertOk();
        $response->assertViewIs('admin.consoles.types.create');

    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $type = factory(ConsoleType::class)->create();
        $response = $this->actingAs($user)->delete(route('type.destroy', ['type' => $type]));

        $response->assertStatus(302);
        $response->assertRedirect(route('console.index'));
        $this->assertSoftDeleted($type);

    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $type = factory(ConsoleType::class)->create();

        $response = $this->actingAs($user)->get(route('type.edit', ['type' => $type]));

        $response->assertOk();
        $response->assertViewIs('admin.consoles.types.edit');
        $response->assertViewHas('consoleType');
        $response->assertSee($type->name);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $name = $this->faker->word . $this->faker->word;
        $response = $this->actingAs($user)->post(route('type.store'), [
            'name' => $name,
        ]);

        $response->assertStatus(302);
        $response->assertRedirect(route('console.index'));
        $this->assertDatabaseHas('console_types', ['name' => $name]);
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Admin\ConsoleTypeController::class,
            'store',
            \App\Http\Requests\Consoles\Type\StoreRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $type = factory(ConsoleType::class)->create();
        $name = $this->faker->word . $this->faker->word;

        $response = $this->actingAs($user)->put(route('type.update', ['type' => $type]), [
            'name' => $name,
        ]);

        $response->assertStatus(302);
        $response->assertRedirect(route('console.index'));
        $this->assertInstanceOf(ConsoleType::class, $type);
        $type->refresh();
        $this->assertEquals($name, $type->name);
        $this->assertDatabaseHas('console_types', ['id' => $type->id, 'name' => $name]);
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Admin\ConsoleTypeController::class,
            'update',
            \App\Http\Requests\Consoles\Type\UpdateRequest::class
        );
    }

    // test cases...
}
