<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\DocumentController
 */
class DocumentControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /**
     * @test
     */
    public function delete_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
        $user = factory(\App\Models\Users\User::class)->create();

        $file = UploadedFile::fake()->image($this->faker->word . '.jpg');
        File::put(public_path('docs').'/' . $file->name, $file);

        $response = $this->actingAs($user)->get(route('document.delete', ['path' => $file->name]));//$file->name . '/' . $file->hashName()

        if(!File::exists(public_path('docs').'/' . $file->name)) {
            assert(true);
        } else {
            File::delete(public_path('docs').'/' . $file->name);
            assert(false);
        }
        $response->assertRedirect(route('document.index'));
//        Storage::disk(public_path())->assertMissing('docs/' . $file->name);
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();

        $response = $this->actingAs($user)->get(route('document.index'));

        $response->assertOk();
        $response->assertViewIs('admin.doc.index');
        $response->assertViewHas('docs');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function upload_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();

        $file = UploadedFile::fake()->image($this->faker->word . '.jpg');

        $response = $this->actingAs($user)->post(route('document.upload'), [
            'file' => $file,
        ]);

        $response->assertStatus(302);
        $response->assertRedirect(route('document.index'));
        assert(File::exists(public_path('docs').'/' . $file->name));
        File::delete(public_path('docs').'/' . $file->name);
    }

    // test cases...
}
