<?php

namespace Tests\Feature\Http\Controllers\Admin;

use App\Models\Inventory\InventoryCategory;
use App\Models\Inventory\InventoryItem;
use App\Models\Language\Language;
use App\Models\Locations\Location;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\InventoryController
 */
class InventoryControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();

        $response = $this->actingAs($user)->get(route('inventory.create'));

        $response->assertOk();
        $response->assertViewIs('admin.inventory.create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $inventory = Helpers::createInventoryItem();
        $response = $this->actingAs($user)->delete(route('inventory.destroy', ['inventory' => $inventory->id]));

        $response->assertRedirect(route('inventory.index'));
        foreach (Language::all() as $language) {
            $this->assertSoftDeleted('inventory_items', ['id' => $inventory->id, 'language_id' => $language->id]);
        }

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $inventory = Helpers::createInventoryItem();
        $response = $this->actingAs($user)->get(route('inventory.edit', ['inventory' => $inventory->id]));

        $response->assertOk();
        $response->assertViewIs('admin.inventory.edit');
        $response->assertViewHas('inventoryItem');
        $response->assertSee($inventory->name);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();

        $response = $this->actingAs($user)->get(route('inventory.index'));

        $response->assertOk();
        $response->assertViewIs('admin.inventory.index');
        $response->assertViewHas('inventoryItems');
        foreach (InventoryItem::all() as $item) {
            $response->assertSee($item->name);
        }
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $location = factory(Location::class)->create();
        $category = factory(InventoryCategory::class)->create();
        $data = [
            'serial_id' => $this->faker->word,
            'inventory_id' => $this->faker->word,
            'category_id' => $category->id,
            'location_id' => $location->id,
        ];
        foreach (Language::all() as $language) {
            $data['name-' . $language->id] = $this->faker->name;
        }
        $response = $this->actingAs($user)->post(route('inventory.store'), $data);

        $response->assertStatus(302);
        $response->assertRedirect(route('inventory.index'));
        foreach (Language::all() as $language) {
            $this->assertDatabaseHas('inventory_items', [
                'name' => $data['name-' . $language->id],
                'language_id' => $language->id,
            ]);
        }
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Admin\InventoryController::class,
            'store',
            \App\Http\Requests\Inventory\StoreRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $inventory = Helpers::createInventoryItem();
        $data = [
            'serial_id' => $inventory->serial_id,
            'inventory_id' => $inventory->inventory_id,
            'category_id' => $inventory->category_id,
            'location_id' => $inventory->location_id,
        ];
        foreach (Language::all() as $language) {
            $data['name-' . $language->id] = $this->faker->name;
        }
        $response = $this->actingAs($user)->put(route('inventory.update', ['inventory' => $inventory->id]), $data);

        $response->assertStatus(302);
        $response->assertRedirect(route('inventory.index'));
        foreach (Language::all() as $language) {
            $this->assertDatabaseHas('inventory_items', [
                'name' => $data['name-' . $language->id],
                'serial_id' => $inventory->serial_id,
                'inventory_id' => $inventory->inventory_id,
                'category_id' => $inventory->category_id,
                'location_id' => $inventory->location_id,
            ]);
        }
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Admin\InventoryController::class,
            'update',
            \App\Http\Requests\Inventory\UpdateRequest::class
        );
    }

    // test cases...
}
