<?php

namespace Tests\Feature\Http\Controllers\Admin;

use App\Models\Language\Language;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\LocationStatusController
 */
class LocationStatusControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();

        $response = $this->actingAs($user)->get(route('status.create'));

        $response->assertOk();
        $response->assertViewIs('admin.locations.status.create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $status = Helpers::createLocationStatus();

        $response = $this->actingAs($user)->delete(route('status.destroy', ['status' => $status->id]));

        $response->assertStatus(302);
        $response->assertRedirect(route('location.index'));
        foreach (Language::all() as $language) {
            $this->assertSoftDeleted('location_statuses', [
                'id' => $status->id,
                'language_id' => $language->id,
            ]);
        }

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $status = Helpers::createLocationStatus();
        $response = $this->actingAs($user)->get(route('status.edit', ['status' => $status->id]));

        $response->assertOk();
        $response->assertViewIs('admin.locations.status.edit');
        $response->assertViewHas('status');
        $response->assertSee($status->name);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $data = [
            'opened' => $this->faker->boolean,
        ];
        foreach (Language::all() as $language) {
            $data['name-' . $language->id] = $this->faker->name;
        }
        $response = $this->actingAs($user)->post(route('status.store'), $data);

        $response->assertStatus(302);
        $response->assertRedirect(route('location.index'));
        foreach (Language::all() as $language) {
            $this->assertDatabaseHas('location_statuses', [
                'name' => $data['name-' . $language->id],
                'opened' => $data['opened'],
            ]);
        }

    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Admin\LocationStatusController::class,
            'store',
            \App\Http\Requests\Locations\Status\StoreRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\Users\User::class)->create();
        $status = Helpers::createLocationStatus();
        $data = [
            'opened' => $this->faker->boolean,
        ];
        foreach (Language::all() as $language) {
            $data['name-' . $language->id] = $this->faker->name;
        }
        $response = $this->actingAs($user)->put(route('status.update', ['status' => $status->id]), $data);

        $response->assertStatus(302);
        $response->assertRedirect(route('location.index'));
        foreach (Language::all() as $language) {
            $this->assertDatabaseHas('location_statuses', [
                'id' => $status->id,
                'name' => $data['name-' . $language->id],
                'opened' => $data['opened'],
            ]);
        }

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Admin\LocationStatusController::class,
            'update',
            \App\Http\Requests\Locations\Status\UpdateRequest::class
        );
    }

    // test cases...
}
