<?php
//
//namespace Tests\Feature\Http\Controllers\Admin;
//
//use Illuminate\Foundation\Testing\RefreshDatabase;
//use Illuminate\Foundation\Testing\WithFaker;
//use Tests\TestCase;
//
///**
// * @see \App\Http\Controllers\Admin\SubpageController
// */
//class SubpageControllerTest extends TestCase
//{
//    use RefreshDatabase, WithFaker;
//
//    public function setUp(): void
//    {
//        parent::setUp();
//        $this->seed();
//    }
//
//    /**
//     * @test
//     */
//    public function create_returns_an_ok_response()
//    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
//
//        $user = factory(\App\Models\Users\User::class)->create();
//
//        $response = $this->actingAs($user)->get(route('subnavigation.create'));
//
//        $response->assertOk();
//        $response->assertViewIs();
//
//        // TODO: perform additional assertions
//    }
//
//    /**
//     * @test
//     */
//    public function destroy_returns_an_ok_response()
//    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
//
//        $user = factory(\App\Models\Users\User::class)->create();
//
//        $response = $this->actingAs($user)->delete(route('subnavigation.destroy', ['subnavigation' => $subnavigation]));
//
//        $response->assertOk();
//        $this->assertDeleted($subnavigation);
//
//        // TODO: perform additional assertions
//    }
//
//    /**
//     * @test
//     */
//    public function edit_returns_an_ok_response()
//    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
//
//        $user = factory(\App\Models\Users\User::class)->create();
//
//        $response = $this->actingAs($user)->get(route('subnavigation.edit', ['subnavigation' => $subnavigation]));
//
//        $response->assertOk();
//        $response->assertViewIs();
//
//        // TODO: perform additional assertions
//    }
//
//    /**
//     * @test
//     */
//    public function public_returns_an_ok_response()
//    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
//
//        $user = factory(\App\Models\Users\User::class)->create();
//
//        $response = $this->actingAs($user)->get(route('subnavigation.public', ['subnavigation' => $subnavigation]));
//
//        $response->assertRedirect(withInput());
//
//        // TODO: perform additional assertions
//    }
//
//    /**
//     * @test
//     */
//    public function reorder_returns_an_ok_response()
//    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
//
//        $user = factory(\App\Models\Users\User::class)->create();
//
//        $response = $this->actingAs($user)->post(route('subnavigation.reorder'), [
//            // TODO: send request data
//        ]);
//
//        $response->assertOk();
//
//        // TODO: perform additional assertions
//    }
//
//    /**
//     * @test
//     */
//    public function store_returns_an_ok_response()
//    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
//
//        $user = factory(\App\Models\Users\User::class)->create();
//
//        $response = $this->actingAs($user)->post(route('subnavigation.store'), [
//            // TODO: send request data
//        ]);
//
//        $response->assertRedirect(withInput($request->only('url', 'order', 'name-1', 'name-2')));
//
//        // TODO: perform additional assertions
//    }
//
//    /**
//     * @test
//     */
//    public function store_validates_with_a_form_request()
//    {
//        $this->assertActionUsesFormRequest(
//            \App\Http\Controllers\Admin\SubpageController::class,
//            'store',
//            \App\Http\Requests\Navigation\Subpage\StoreRequest::class
//        );
//    }
//
//    /**
//     * @test
//     */
//    public function update_returns_an_ok_response()
//    {
//        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
//
//        $user = factory(\App\Models\Users\User::class)->create();
//
//        $response = $this->actingAs($user)->put(route('subnavigation.update', ['subnavigation' => $subnavigation]), [
//            // TODO: send request data
//        ]);
//
//        $response->assertRedirect(withInput($request->only('url', 'order', 'name-1', 'name-2')));
//
//        // TODO: perform additional assertions
//    }
//
//    /**
//     * @test
//     */
//    public function update_validates_with_a_form_request()
//    {
//        $this->assertActionUsesFormRequest(
//            \App\Http\Controllers\Admin\SubpageController::class,
//            'update',
//            \App\Http\Requests\Navigation\Subpage\UpdateRequest::class
//        );
//    }
//
//    // test cases...
//}
